### PR TITLE
Update README for Fedora

### PR DESCRIPTION
**Pull request by tpoisot**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Perhaps the text should read:

> For Debian/Ubuntu based variants, you'll need `libzmq-dev` or `libzmq3-dev`
> For RedHat/CentOS/Fedora based variants, you'll need `zeromq` and `zeromq-devel`.

**Comment by tpoisot** [comment]
Agreed, changed.

**Comment by willwhitney** [comment]
Sounds good, thanks for the PR!

**Comment by tpoisot** [comment]
Well, thanks for Hydrogen! I'm starting to *really* like it.

**Comment by willwhitney** [comment]
:D

**Pull request merged**
