### PR TITLE
Add watch command

### PR DESCRIPTION
**Pull request by terraqout**

### CODE REVIEW

**Comment by terraqout** [comment]
@rgbkrk or @willwhitney can you review this and merge?

**Comment by willwhitney** [comment]
Sorry about the delay — this looks great.

**Comment by willwhitney** [comment]
Shipped as v0.6.5.

@terraqout Since you've done a bunch of good work on the project, I've given you collaborator access on the repo. Thanks for the hard work!

**Comment by terraqout** [comment]
@willwhitney thanks for confidence.

**Pull request merged**
