### PR TITLE
Switch kernel command

### PR DESCRIPTION
**Pull request by slavaGanzin**
out

### CODE REVIEW

**Comment by terraqout** [comment]
Grammar to kernel mapping now saved.

**Comment by terraqout** [comment]
https://github.com/willwhitney/hydrogen/issues/34 close this when merged

**Comment by terraqout** [comment]
https://github.com/willwhitney/hydrogen/issues/40 Linked for further improve

**Comment by willwhitney** [comment]
Sorry I've been absent — I've been out of town at a conference, then finishing up PhD applications.

This looks good to me. Assuming you've tested it a bit, merge away!

**Comment by slavaGanzin** [comment]
@willwhitney Congratulations with your scientific success.

**Comment by stevengj** [comment]
Looks great!  Would be nice to have some documentation somewhere, both of the switching feature and the new config options (e.g. the `grammarToKernel` config, which I guess allows you to specify a default kernel for a given language).

**Comment by slavaGanzin** [comment]
@stevengj Hello and thanks for your work on julia.

Yeah you are right, I'll add some.

**Comment by slavaGanzin** [comment]
My english isn't great, so edit if you want https://github.com/willwhitney/hydrogen/commit/c23f5b1c8c3c243673424c3efd43205fbb8adee7

**Comment by willwhitney** [comment]
Just made some minor copy edits. Thanks for getting this working!

**Comment by willwhitney** [comment]
I wonder if as the next step we can merge the two config fields we have now. We could pull out the "Select Kernel" command to the top level, then have it list all installed kernels, and save the selection into the `languageMappings` field. That way the user would never have to manage JSON directly.

Ideally it would be added to the `activationCommands` field in `package.json` so that the user can select what kernel to use before running something.

**Comment by slavaGanzin** [comment]
I'll appreciate if this would be done by someone :smile:

**Pull request merged**
